{ pkgs, misc, ... }: {
  # User Customizations
  # Generated by Fleek - do not modify
   home.shellAliases = {
    bluefin = "cd ~/projects/ublue/bluefin";
    cdfleek = "cd ~/projects/ublue/fleek";
    fleeks = "cd ~/.local/share/fleek";
    gcb = "git checkout -b";
    gitmain = "git checkout main && git pull";
    projects = "cd ~/projects";
    ublue = "cd ~/projects/ublue";
    };
}
